services:
  clickhouse:
      image: 'clickhouse/clickhouse-server'
      container_name: clickhouse    
      environment:
          - CLICKHOUSE_DB=${CLICKHOUSE_DB}
          - CLICKHOUSE_USER=${CLICKHOUSE_USER}
          - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
          - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
        #   - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS: 1
      ports:
          - '8123:8123'
          - '9000:9000'
      volumes:
          - ./config/config.xml:/etc/clickhouse-server/config.d/config.xml
          - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml
          - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
          - clickhouse_data:/var/lib/clickhouse

      restart: unless-stopped
      healthcheck:
          test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
          interval: 10s
          timeout: 5s
          retries: 5
networks:
  cdc_global_network:
    external: true
volumes:
  clickhouse_data: