spring:
  application:
    name: autocart
  datasource:
    url: jdbc:postgresql://localhost:5432/autocart
    username: development_admin
    password: 900913
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update # Options: none, update, create, create-drop, validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true

