{
    "name": "mongodb-connector",
    "config": {
        "connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
        "mongodb.connection.string": "",
        "topic.prefix": "mongoDB",
        "database.include.list": "tracking_db",
        "collection.include.list": "tracking_db.behaviors",
        "capture.mode": "change_streams_update_full",
        "tombstones.on.delete": "false"
    }
}